package util.events;

public enum Event {
    ADD_CONT, DELETE_CONT, UPDATE_CONT,
    ADD_CERERE, APPROVE_CERERE, REJECT_CERERE, DELETE_CERERE,
    DELETE_PRIETEN,
    ADD_MESAJ,
    ADD_EVENIMENT, DELETE_EVENIMENT,
    ADD_PARTICIPANT, DELETE_PARTICIPANT
}
